version: "3"
services:
    app:
      build:
        context: app
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
        dockerfile: Dockerfile
      container_name: doker-node-mongo
      restart: always
      build: .
      ports:
        - '80:3000'
      links:
        - mongo
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - '27017:27017'